#!/bin/sh
#
# Copyright (c) 2014 The Linux Foundation. All rights reserved.
# Copyright (C) 2011-2012 OpenWrt.org
#

[ -e /etc/config/ubootenv ] && exit 0

touch /etc/config/ubootenv

. /lib/ipq806x.sh
. /lib/uboot-envtools.sh
. /lib/functions.sh

board=$(ipq806x_board_name)

default_uboot_env () {
	UBOOTENV_PART=$(cat /proc/mtd | grep APPSBLENV)
	echo $UBOOTENV_PART | sed \
		's/^\(mtd[0-9]*\): \([0-9]*\) \([0-9]*\) \"APPSBLENV\"/\/dev\/\1\t0x00000000\t0x\2\t0x\3/g'
}

case "$board" in
ap148 | \
db149 | \
db147)
	ubootenv_add_uci_config "/dev/mtd0" "0x0" "0x40000" "0x20000" "2"
	;;
*)
	env=$(default_uboot_env)
	[ -n "${env}" ] && ubootenv_add_uci_config $env
	;;
esac

config_load ubootenv
config_foreach ubootenv_add_app_config ubootenv

exit 0
